# -*- coding: utf-8 -*-
"""SCT_DS_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgDqU7U2Ha7TiAKesRCppOgzk7GLkViA

**CODE FOR UPLOADING MY EXCEL FILES**
"""

from google.colab import files
uploaded = files.upload()

"""**MAIN CODE**"""

import pandas as pd
from google.colab import files

print("⬆️ Please upload 'players_100plus_2016.csv' and 'teams_200plus_2016.csv'")
uploaded = files.upload()

players_df = pd.read_csv("players_100plus_2016.csv")
teams_df = pd.read_csv("teams_200plus_2016.csv")

print("✅ Players runs in 2016:")
print(players_df, "\n")

highest_player = players_df.loc[players_df["Runs"].idxmax()]
print("🏏 Highest Player Runs in 2016:")
print(highest_player, "\n")

print("✅ Teams runs in 2016:")
print(teams_df, "\n")

highest_team = teams_df.loc[teams_df["Total_Runs"].idxmax()]
print("🏏 Highest Team Runs in 2016:")
print(highest_team, "\n")

print(f"Total players with 100+ runs: {len(players_df)}")
print(f"Total teams with 200+ runs: {len(teams_df)}")

"""**BAR GRAPHS FOR THE DATA**"""

import pandas as pd
from google.colab import files
import matplotlib.pyplot as plt

print("⬆️ Please upload 'players_100plus_2016.csv' and 'teams_200plus_2016.csv'")
uploaded = files.upload()

players_df = pd.read_csv("players_100plus_2016.csv")
teams_df = pd.read_csv("teams_200plus_2016.csv")

# Top 5 players
top_players = players_df.sort_values(by="Runs", ascending=False).head(5)

plt.figure(figsize=(10,5))  # smaller figure
colors = ['red' if player in top_players["Player"].values else 'skyblue' for player in players_df["Player"]]
plt.bar(players_df["Player"], players_df["Runs"], color=colors)
plt.xticks(rotation=90, fontsize=10)
plt.yticks(fontsize=10)
plt.title("Distribution of Runs by Players (Top 5 Highlighted) - IPL 2016", fontsize=12)
plt.xlabel("Player", fontsize=10)
plt.ylabel("Runs", fontsize=10)
plt.tight_layout()
plt.show()

# Top 5 teams
top_teams = teams_df.sort_values(by="Total_Runs", ascending=False).head(5)

plt.figure(figsize=(8,4))  # smaller figure
colors = ['green' if team in top_teams["Team"].values else 'orange' for team in teams_df["Team"]]
plt.bar(teams_df["Team"], teams_df["Total_Runs"], color=colors)
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)
plt.title("Distribution of Total Runs by Teams (Top 5 Highlighted) - IPL 2016", fontsize=12)
plt.xlabel("Team", fontsize=10)
plt.ylabel("Total Runs", fontsize=10)
plt.tight_layout()
plt.show()

"""### *`SUMMARY:`* So my analysis shows the following-
              Highest run scorer in 2016 IPL: Virat Kohli
              Highest Team runs in 2016 IPL: RCB
"""